apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: kwilliams
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: harbor.dev.afsmtddso.com/kwilliams-harbor-project/db:49d0fd3-0661bad
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: db-secret
